from odenarium.fun import fun
from odenarium.YorN import YorN
from odenarium.isint import isint
from odenarium.isfloat import isfloat
from odenarium.inInt import inInt
from odenarium.inFl import inFl
from odenarium.inFu import inFu
from odenarium.inN import inN
from odenarium.inN0 import inN0
from odenarium.needokr import needokr
from odenarium.isvar import isvar
from odenarium.invar import invar
from odenarium.warprint import warprint
from odenarium.erprint import erprint
